/**
 * Python-compatible canonical JSON + digest.
 *
 * This module exists because JavaScript's `JSON.stringify` is NOT equivalent to
 * Python's `json.dumps`. The onestep `submission_digest` is computed in Python as:
 *
 *   sha256(json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True))
 *
 * A naive TS implementation diverges in several places and silently breaks
 * idempotency (the server raises ExecutionConflict for an identical submission):
 *
 *   1. Float formatting. Python keeps a trailing ".0" for integral floats
 *      (`1.0` -> "1.0"); JS prints `1`. Python also uses repr-style shortest
 *      round-trip with `e+NN` exponents; JS uses different thresholds.
 *   2. Integer vs float. Both languages distinguish them, so `{"i":1,"f":1.0}`
 *      must serialize as `{"i":1,"f":1.0}` — JS collapses both to `1`.
 *   3. Datetime. Python emits `2026-09-17T10:07:00.123456+00:00`;
 *      JS `toISOString()` emits `2026-09-17T10:07:00.123Z`.
 *   4. Non-ASCII. Python with `ensure_ascii=True` escapes to \uXXXX including
 *      surrogate pairs; `JSON.stringify` emits raw UTF-8.
 *
 * The authoritative check is `tests/canonical.test.ts`, which asserts against
 * `fixtures/golden.json` generated by the Python implementation itself.
 */

/**
 * A float that must be formatted with Python's `repr` semantics.
 *
 * Note: written without TypeScript parameter properties because Node's
 * strip-only type erasure rejects them.
 */
export class PyFloat {
  readonly value: number;
  constructor(value: number) {
    this.value = value;
  }
}

/**
 * A datetime carrying an explicit, Python-`isoformat()`-shaped string.
 *
 * Needed because Python emits `+00:00` (and microsecond precision) where JS
 * `toISOString()` emits `Z` (and milliseconds), and the difference changes the
 * digest.
 */
export class PyDateTime {
  readonly iso: string;
  constructor(iso: string) {
    this.iso = iso;
  }
}

const ESCAPES: Record<string, string> = {
  '"': '\\"',
  '\\': '\\\\',
  '\n': '\\n',
  '\r': '\\r',
  '\t': '\\t',
  '\b': '\\b',
  '\f': '\\f',
};

/**
 * Escape a string the way Python's json.dumps does with ensure_ascii=True.
 *
 * Printable ASCII stays literal; everything else becomes \uXXXX, using a
 * surrogate pair for astral-plane code points (matching CPython, which
 * operates on UTF-16 code units here).
 */
function escapeString(value: string): string {
  let out = '"';
  for (let i = 0; i < value.length; i++) {
    const code = value.charCodeAt(i);
    const ch = value[i];
    if (Object.prototype.hasOwnProperty.call(ESCAPES, ch)) {
      out += ESCAPES[ch];
    } else if (code < 0x20 || code > 0x7e) {
      out += '\\u' + code.toString(16).padStart(4, '0');
    } else {
      out += ch;
    }
  }
  return out + '"';
}

/**
 * Format a number the way Python's `repr` does for floats.
 *
 * Rules matched against CPython behaviour:
 *   - integral floats keep a trailing ".0"          (1.0 -> "1.0", -0.0 -> "-0.0")
 *   - shortest round-trip representation            (0.1+0.2 -> "0.30000000000000004")
 *   - scientific notation uses "e+NN"/"e-NN" with a
 *     sign and at least two exponent digits         (1e21 -> "1e+21")
 *   - Python switches to exponent form at >=1e16 and <1e-4
 *     (JS switches at >=1e21), so we cannot borrow JS thresholds
 *
 * This is the single highest-risk function in the client; it is covered
 * exhaustively by the float vectors in fixtures/golden.json.
 */
export function formatPyFloat(value: number): string {
  if (Number.isNaN(value)) throw new RangeError('cannot serialize NaN');
  if (!Number.isFinite(value)) throw new RangeError('cannot serialize Infinity');

  // Exact zero: preserve the sign of negative zero, as CPython does.
  if (value === 0) return Object.is(value, -0) ? '-0.0' : '0.0';

  const negative = value < 0;
  const abs = Math.abs(value);

  // CPython's repr uses exponent notation when the decimal exponent satisfies
  // exp < -4 || exp >= 16. Deriving the exponent with Math.log10 is unsafe at
  // boundaries (log10(1e16) can land on 15.999...), so read it from the
  // engine's own shortest round-trip exponential form instead.
  const expForm = abs.toExponential();
  const exp = parseInt(expForm.split('e')[1], 10);
  const useExponent = exp < -4 || exp >= 16;

  let out: string;

  if (useExponent) {
    // `toExponential()` with no argument gives the shortest round-trip
    // mantissa, matching repr. Python always writes a signed, >=2-digit
    // exponent: 1e+21, 1e-07.
    const [mantissa] = expForm.split('e');
    const sign = exp < 0 ? '-' : '+';
    const expStr = Math.abs(exp).toString().padStart(2, '0');
    out = `${mantissa}e${sign}${expStr}`;
  } else {
    // Plain decimal notation with the shortest round-trip digits.
    let plain = abs.toString();
    if (plain.includes('e') || plain.includes('E')) {
      // JS chose exponent form where Python would not; expand it.
      plain = expandExponent(abs);
    }
    out = plain;
  }

  // Python always shows a fractional part for floats: append ".0" when the
  // emitted form is integral (and is not in exponent notation).
  if (!out.includes('e') && !out.includes('.')) {
    out += '.0';
  }

  return negative ? '-' + out : out;
}

/** Expand a JS exponent-form number into plain decimal notation. */
function expandExponent(abs: number): string {
  const s = abs.toExponential();
  const [mantissa, e] = s.split('e');
  const exp = parseInt(e, 10);
  const negExp = exp < 0;
  const digitsOnly = mantissa.replace('.', '');
  const dotPos = (mantissa.indexOf('.') === -1 ? mantissa.length : mantissa.indexOf('.')) + exp;

  if (dotPos <= 0) {
    return '0.' + '0'.repeat(-dotPos) + digitsOnly;
  }
  if (dotPos >= digitsOnly.length) {
    return digitsOnly + '0'.repeat(dotPos - digitsOnly.length);
  }
  return digitsOnly.slice(0, dotPos) + '.' + digitsOnly.slice(dotPos);
}

/** Kinds of value the encoder accepts. */
export type CanonicalValue =
  | null
  | boolean
  | number
  | string
  | PyFloat
  | PyDateTime
  | CanonicalValue[]
  | { [key: string]: CanonicalValue };

/**
 * Serialize a value exactly as Python's
 * `json.dumps(v, sort_keys=True, separators=(",", ":"), ensure_ascii=True)` would.
 *
 * `sort_keys=True` means object keys are ordered by Unicode code point.
 */
export function canonicalize(value: CanonicalValue): string {
  if (value === null) return 'null';

  if (value instanceof PyFloat) return formatPyFloat(value.value);
  if (value instanceof PyDateTime) return escapeString(value.iso);

  const t = typeof value;
  if (t === 'boolean') return value ? 'true' : 'false';
  if (t === 'string') return escapeString(value as string);
  if (t === 'number') {
    // A plain JS number reaching here came from a JSON-parsed document, so it
    // cannot be distinguished from an int-or-float the Python caller wrote.
    // Treat integral values as ints (matching JSON's default reading) and
    // non-integral as floats; callers that know the true type must wrap in
    // PyFloat.
    const n = value as number;
    if (Number.isInteger(n) && Math.abs(n) < 1e21) return String(n);
    return formatPyFloat(n);
  }

  if (Array.isArray(value)) {
    return '[' + value.map(canonicalize).join(',') + ']';
  }

  if (t === 'object') {
    const obj = value as { [key: string]: CanonicalValue };
    const keys = Object.keys(obj).sort(compareCodePoint);
    const parts: string[] = [];
    for (const key of keys) {
      parts.push(escapeString(key) + ':' + canonicalize(obj[key]));
    }
    return '{' + parts.join(',') + '}';
  }

  throw new TypeError(`cannot canonicalize value of type ${t}`);
}

/** Compare two strings by Unicode code point, matching Python's `sorted`. */
function compareCodePoint(a: string, b: string): number {
  const len = Math.min(a.length, b.length);
  for (let i = 0; i < len; i++) {
    const ca = a.charCodeAt(i);
    const cb = b.charCodeAt(i);
    if (ca !== cb) return ca - cb;
  }
  return a.length - b.length;
}

/**
 * Compute the SHA-256 hex digest of the canonical form, matching
 * `hashlib.sha256(canonical.encode("ascii")).hexdigest()`.
 */
export async function canonicalSha256(value: CanonicalValue): Promise<string> {
  const canonical = canonicalize(value);
  // Node's global crypto.subtle is available in Node 16+ and in edge runtimes.
  const bytes = new TextEncoder().encode(canonical);
  const hash = await crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(hash))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

/**
 * Build the `submission_digest` for a submit request.
 *
 * Mirrors ExecutionStateMachine._submit in
 * plugins/onestep-sql/src/onestep_sql/_shared/execution/machine.py:402-419.
 * The digest covers namespace, task_name, payload, metadata, delay_s and
 * expires_at — so a change to any of them is a conflict for the same
 * idempotency key.
 */
export async function submissionDigest(input: {
  namespace: string;
  taskName: string;
  payload: CanonicalValue;
  metadata: CanonicalValue;
  delayS: number | null;
  expiresAt: string | null;
}): Promise<string> {
  const digestPayload: { [key: string]: CanonicalValue } = {
    namespace: input.namespace,
    task_name: input.taskName,
    payload: input.payload,
    metadata: input.metadata,
    delay_s: input.delayS === null ? null : new PyFloat(input.delayS),
    expires_at: input.expiresAt,
  };
  return canonicalSha256(digestPayload);
}
