// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CopyImport: typeof import('./components/CopyImport.vue')['default']
    CourseLink: typeof import('./components/CourseLink.vue')['default']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    ModuleInfo: typeof import('./components/ModuleInfo.vue')['default']
    ProjectInfo: typeof import('./components/ProjectInfo.vue')['default']
    TagPage: typeof import('./components/TagPage.vue')['default']
    Tags: typeof import('./components/Tags.vue')['default']
  }
}
